# Generated by Django 2.2.7 on 2020-01-06 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=100, null=True, verbose_name='photographer Name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('uploadImg', models.ImageField(default='pic_pho/None/no-img.jpg', upload_to='pic_pho/')),
            ],
        ),
        migrations.CreateModel(
            name='Uploadimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('imgupload', models.ImageField(upload_to='pic_folder')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pho.Photographer')),
            ],
        ),
    ]
