# Generated by Django 2.2.7 on 2020-01-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter'),
        ),
    ]
