# Generated by Django 2.2.7 on 2020-01-06 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title Name')),
                ('plstext', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stext')),
                ('plstate', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('pllat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lat')),
                ('pllang', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lang')),
                ('pldesc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Name')),
                ('uploadImg', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('desc', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('main_img', models.BooleanField(default=False)),
                ('plname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_data', to='place.Place')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pho_data', to='pho.Photographer')),
            ],
        ),
        migrations.CreateModel(
            name='GustComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment Title')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('status', models.BooleanField(default=False)),
                ('plname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('cdetail', models.TextField(blank=True, null=True, verbose_name='Detail')),
                ('plname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place')),
                ('pname', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pho.Photographer')),
            ],
        ),
    ]
